version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: test@pgadmin.com

      PGADMIN_DEFAULT_PASSWORD: test
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "80:80"
    networks:
      - my_network


  jupyter:
    # image: jupyter/minimal-notebook:latest
    build:
      context: .
      dockerfile: jupyter-dockerfile
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./dags/finance:/home/jovyan/work/finance
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - tmp_dir=/tmp
      - NotebookApp.token=
      - NotebookApp.password=
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    external: true

volumes:
  # postgres_data:
  pgadmin_data:
  data: 
