version: '3.7'

x-path: &volume
    volume:
        - &DagPath './airflow/dags:/opt/airflow/dags'
        - &PlugPath './airflow/plugin:/opt/airflow/plugin'
        - &Postgres './pgdata:/var/lib/postgresql/data'
        - &ConfigPath './airflow/airflow.cfg:/opt/airflow/airflow.cfg'
        - &DataRange './history:/opt/airflow/history'
        - &DataRangePath "./airflow/dags/history:/opt/airflow/dags/history"

x-connections: &commonConnections
    AIRFLOW__CORE__EXECUTOR: 'CeleryExecutor'
    # AIRFLOW__CELERY__RESULT_BACKEND: 'db+postgresql://airflow:airflow@postgres:5432/airflow'
    AIRFLOW__CELERY__BROKER_URL: 'redis://redis:6379/1'
    AIRFLOW__CORE__FERNET_KEY: 'hQIPxfJ1mXDdtP/KDfzxAKBoMi993qWJZEisuJo7eLA='
    AIRFLOW__WEBSERVER__SECRET_KEY: 'a4imZCY/A/8U3gFjw8QfN8YpWaeIK2bSjlfCmE7iYT8='

x-airflow-environment: &airflowEnvironment
    # AIRFLOW__CORE__SQL_ALCHEMY_CONN: 'postgresql+psycopg2://airflow:airflow@postgres:5432/airflow'
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: 'postgresql+psycopg2://airflow:airflow@postgres:5432/airflow'
    PYTHONPATH: '/opt/airflow/dags'
    AIRFLOW_HOME: '/opt/airflow'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'FALSE'
    AIRFLOW__WEBSERVER__NAVBAR_COLOR: '#bca0dc'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'TRUE'
    AIRFLOW__CORE__LAZY_LOAD_PLUGINS: 'FALSE'

x-default-user: &defaultUser
    USERNAME: 'admin'
    PASSWORD: 'admin'
    ROLE: 'Admin'
    FIRSTNAME: 'Firstname'
    LASTNAME: 'Lastname'
    EMAIL: 'username@domain.com'
x-crawler: &crawler
    # user: "root"
    # password: "password"
    host: "mongodb"
    port: "27017"


services:
    postgres:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD: airflow
            POSTGRES_DB: airflow
        volumes:
            - *Postgres
    redis:
        image: redis:6.0.9-alpine


    scheduler:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres
            # - mongodb
            # - selenium
        environment:
            <<: *commonConnections
            <<: *airflowEnvironment
        volumes:
            # - *ConfigPath
            - *DagPath
            - *PlugPath
        command: scheduler

    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - scheduler
        environment:
            <<: *commonConnections
            <<: *airflowEnvironment
            <<: *defaultUser
            <<: *crawler
        ports:
            - 8085:8080
        volumes:
            # - *ConfigPath
            - *DagPath
            - *PlugPath
            - *DataRangePath
        command: webserver

    flower:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - scheduler
            - redis
        environment:
            <<: *commonConnections
            <<: *airflowEnvironment
            <<: *defaultUser
        ports:
            - 5555:5555
        volumes:
            # - *ConfigPath
            - *DagPath
            - *PlugPath
        command: flower

    worker:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            <<: *commonConnections
            <<: *airflowEnvironment
        volumes:
            # - *ConfigPath
            - *DagPath
            - *PlugPath
        command: worker


    # mongodb:
    #     image: mongo
    #     # volumes:
    #     # - './data:/data/db'
    #     environment:
    #         - MONGO_INITDB_ROOT_USERNAME=admin
    #         - MONGO_INITDB_ROOT_PASSWORD=admin
    #     ports:
    #     - 27017:27017


    # selenium:
    #     image: seleniarm/standalone-chromium
    #     ports:
    #     - 4444:4444

